# Generated by Django 6.0.5 on 2026-05-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido materno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50, verbose_name='Apellido paterno'),
        ),
    ]
