# Generated by Django 6.0.5 on 2026-05-19 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_usuario_options_remove_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categotias',
                'ordering': ['nombre_categoria'],
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biblioteca.categoria', verbose_name='Categoria'),
        ),
    ]
